package edu.eci.cosw.jpa.sample.model;
// Generated Mar 9, 2016 7:01:57 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;

/**
 * Consultas generated by hbm2java
 */
@Entity(name = "Consulta")
@Table(name = "CONSULTAS")
public class Consulta  implements java.io.Serializable {

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns({
            @JoinColumn(name="PACIENTES_id"),
            @JoinColumn(name="PACIENTES_tipo_id")
    })
    private Paciente paciente;

    @Id
    @Column(name="IdCONSULTAS", nullable=false)
    @GeneratedValue
    private Integer idConsultas;

    @Column(name="fecha_y_hora" ,nullable=false)
    private Date fechaYHora;

    @Column(name="resumen",length=45,nullable=false)
    private String resumen;

    public Consulta() {
    }

    public Consulta(Date fechaYHora, String resumen ,Paciente paciente) {
       this.fechaYHora = fechaYHora;
       this.resumen = resumen;
       this.paciente=paciente;
    }


    public Integer getIdConsultas() {
        return this.idConsultas;
    }
    
    public void setIdConsultas(Integer idConsultas) {
        this.idConsultas = idConsultas;
    }

    public Date getFechaYHora() {
        return this.fechaYHora;
    }
    
    public void setFechaYHora(Date fechaYHora) {
        this.fechaYHora = fechaYHora;
    }
    public String getResumen() {
        return this.resumen;
    }
    
    public void setResumen(String resumen) {
        this.resumen = resumen;
    }


    public Paciente getPaciente() {
        return paciente;
    }

    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

}


