package edu.eci.cosw.jpa.sample.model;
// Generated Mar 9, 2016 7:01:57 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TiposPoliza generated by hbm2java
 */
@Entity(name= "TipoPoliza")
@Table(name="TIPOS_POLIZA")
public class TipoPoliza  implements java.io.Serializable {

    @Id
    @GeneratedValue
    @Column(name = "codigo_poliza",nullable = false,length = 11)
    private int codigoPoliza;

    @Column(name = "nombre", nullable = false, length = 45)
    private String nombre;

    @Column(name = "descripcion", nullable = false, length = 45)
    private String descripcion;

    @Column(name = "monto_maximo", nullable = false,length = 20)
    private long montoMaximo;

    @OneToMany(mappedBy = "tiposPoliza")
    private Set<PolizaAprobada> polizas_aprobadas=new HashSet<>();

    public TipoPoliza() {
    }
    public TipoPoliza(int codigoPoliza, String nombre, String descripcion, long montoMaximo ) {
        this.codigoPoliza = codigoPoliza;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.montoMaximo = montoMaximo;
    }
	
    public TipoPoliza(int codigoPoliza, String nombre, String descripcion, long montoMaximo ,Set<PolizaAprobada> polizas) {
        this.codigoPoliza = codigoPoliza;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.montoMaximo = montoMaximo;
        this.polizas_aprobadas=polizas;
    }
   
    public int getCodigoPoliza() {
        return this.codigoPoliza;
    }
    
    public void setCodigoPoliza(int codigoPoliza) {
        this.codigoPoliza = codigoPoliza;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public long getMontoMaximo() {
        return this.montoMaximo;
    }
    
    public void setMontoMaximo(long montoMaximo) {
        this.montoMaximo = montoMaximo;
    }

    public Set<PolizaAprobada> getPolizas_aprobadas() {
        return polizas_aprobadas;
    }

    public void setPolizas_aprobadas(Set<PolizaAprobada> polizas_aprobadas) {
        this.polizas_aprobadas = polizas_aprobadas;
    }
}


